services:
  mongo-1:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    networks:
      - mongo-net
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
  
  mongo-2:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    networks:
      - mongo-net
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
  
  mongo-3:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    networks:
      - mongo-net
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongo-init:
    image: ghcr.io/qcynaut/mongodb-init:latest
    networks:
      - mongo-net
    environment:
      MONGODB_HOSTS: "mongo-1:27017,mongo-2:27017,mongo-3:27017"
    restart: no
    depends_on:
      mongo-1:
        condition: service_healthy
      mongo-2:
        condition: service_healthy
      mongo-3:
        condition: service_healthy


networks:
  mongo-net:
    driver: bridge